[package]
name="image_dctrs"
version="0.0.1"
authors = ["Destiny Ifeanyi<ifeanyiotah001@gmail.com>"]
edition="2018"

[lib]
crate-type = ["cdylib"]
path = "src/lib.rs"
[dependencies]
js-sys = "0.3.69"
wasm-bindgen = "0.2.92"
